### ISSUE TITLE
Monitor won’t go into suspend mode after installing cfs-zen tweak - Kubuntu 22.04.

### ISSUE THREAD

**Issue by snivlle** [igo95862/cfs-zen-tweaks#13]
Dear Igo,
Thank you very much for your wonderful tweak utility - it does indeed seem to make my ubuntu-based KDE Linux desktop environment a bit snappier and more responsive. I am using the “official” ubuntu low-latency kernel (5.15.x).

Unfortunately, ever since installing cfs-zen-tweak (.deb), my monitor won’t go into suspend mode. I had it set to suspend after 7 minutes of idle time (monitor only, the computer itself remains powered up). I’ve tried changing the time until monitor is supposed to suspend, I’ve tried uninstalling cfs-zen-tweak, but nothing has worked to restore my previous configuration. To my knowledge, nothing else has changed on my system and it was working correctly up until I installed cfs-zen. I like the overall improvement that cfs-zen-tweak made on my system, but the monitor-suspend issue is bothersome. I don’t like my screen powered on constantly if I need to step away from my desktop PC. Can you help me, friend?

**Comment by igo95862** [comment]
Hello,

Sorry but I don't see any connection between monitor energy saving mode and this script.

You should be able to change the monitor power saving settings on the KDE's "Energy Savings" page.

![](https://userbase.kde.org/images.userbase/2/2a/PowerDevil1.png)

**Comment by snivlle** [comment]
Hi Igo,

Thanks for getting back to me so quickly. Yes, I’m very familiar with the KDE settings page - the monitor suspend functionality stopped working after I installed cfs-zen-tweak. Even when I try to manually force the monitor to suspend, it just wakes itself back up after 10 or 15 seconds (I have a keyboard shortcut created in KDE settings to do this).

**Comment by igo95862** [comment]
Something is probably waking up the desktop. There is a `org.gnome.Mutter.IdleMonitor` D-Bus service for GNOME to monitor the wake-up. Not sure if KDE has an equivalent. You should debug what is causing wake ups. (web search is your friend)  For example, a mouse pointer might be drifting a few pixels every once in a while.

For example: https://askubuntu.com/questions/202136/how-can-a-script-detect-a-users-idle-time/202145#202145

There is a program called `xprintidle` that can be used to monitor the idle time from the prespective of X server. If the idle time keeps resetting without any input when something is causing the wake-ups.

Again this has nothing to do with this script especially if you uninstalled the package.

**Comment by igo95862** [comment]
For example, today I had issues with my laptop not entering the sleep mode correctly. It turns out one of the USB devices was instantly waking it up.
