### ISSUE TITLE
Error: Package architecture (any) does not match system (amd64)

### ISSUE THREAD

**Issue by norvegum** [igo95862/cfs-zen-tweaks#4]
I'm running Pop!_OS 20.04 and deb installation fails with "Installation Failed. Error while installing package: package architecture (any) does not match system (amd64)" - Any suggestions..?

**Comment by igo95862** [comment]
Which version have you downloaded? Latest version [should have `all` architecture](https://github.com/igo95862/cfs-zen-tweaks/commit/5bb047340e340170a39825423240b9ae21e87f6b) which should install without any issue.

**Comment by norvegum** [comment]
I have 1.0.0 - that's the latest, no? - No, I see now that there are newer ones... Sorry, will try. I used a link on a web page that links to 1.0.0.

**Comment by norvegum** [comment]
I actually used the link on the "Code" page here: 

"Installing
Available on AUR.
Also see releases page for built RPM and DEB packages." 

The link on "releases" points to version 1.0.0. Perhaps change to the releases overview page?

**Comment by igo95862** [comment]
> The link on "releases" points to version 1.0.0. Perhaps change to the releases overview page?

My bad. I will link it to releases page.

**Comment by igo95862** [comment]
@mdtrilby The link should now take to overall releases page. The latest version is 1.2.0

**Comment by norvegum** [comment]
> @mdtrilby The link should now take to overall releases page. The latest version is 1.2.0

Thanks for prompt reply and fix!
