### ISSUE TITLE
Moving to POSIX-compliant sh? (!bashism)

### ISSUE THREAD

**Issue by owl4ce** [igo95862/cfs-zen-tweaks#5]
Hello, I like this tweaks. However,
why not try switching to POSIX-compliant shell for portability like `dash` (as `/bin/sh`) users?

https://github.com/igo95862/cfs-zen-tweaks/blob/fb723db0222bc06a417bc3bafdb7a6ad1d3ed84b/set-cfs-zen-tweaks.bash#L1

In what cases do you have to use `-o pipefail` and `shopt -s extdebug`?

https://github.com/igo95862/cfs-zen-tweaks/blob/fb723db0222bc06a417bc3bafdb7a6ad1d3ed84b/set-cfs-zen-tweaks.bash#L18-L19

If you wish, you can change the shebang from `/bin/bash` to `/usr/bin/env sh` sh or direct `/bin/sh`. `.sh` file suffix is optional.

Thanks for the great tweaks. 🎉

**Comment by igo95862** [comment]
> why not try switching to POSIX-compliant shell for portability like `dash` (as `/bin/sh`) users?

I believe one of the earlier versions used some bash feature and it was very difficult to replicate on POSIX shell.

However, current one can definitely run on POSIX shell. I ran shellcheck and there seems to be no issues. I will add those changes.

> Thanks for the great tweaks.

Glad you liked it.

**Comment by igo95862** [comment]
Not entirely sure what dependency should I put in for DEB package instead of bash...

**Comment by owl4ce** [comment]
> However, current one can definitely run on POSIX shell. I ran shellcheck and there seems to be no issues. I will add those changes.

According to https://unix.stackexchange.com/a/654899
> I suspect that shellcheck has a "POSIX sh mode" and an "other mode" to support bash, dash, and ksh (shellcheck does not claim to support zsh). The pipefail shell option is documented to work with bash, and ksh. The zsh shell has a PIPE_FAIL shell option that can be set in the same way. **The dash shell does not support the option, but if the #!-line mentions dash, shellcheck won't complain about pipefail.**

Ok, `dash` doesn't support `set -o pipefail`. Playing trick to disable `pipefail` on `dash` ..
```sh
set -eEu $( [ "$(readlink -f /proc/$$/exe)" = "$(command -v dash)" ] || echo '-o pipefail' )
```

There's no pipe `|` there, I think `set -o pipefail` is **useless**. Now how about `extdebug` bash feature.

---

> Not entirely sure what dependency should I put in for DEB package instead of bash...

Maybe none for shell-script dependency. 😄

How about switching from **Cmake** to **GNU Make**?

**Comment by igo95862** [comment]
I will just remove `pipefail` and `extdebug` since they don't serve much purpose.

> How about switching from **Cmake** to **GNU Make**?

Technically CMake generates Makefiles for GNU Make. (unless you select Ninja backend)

CMake is used for creating `.deb` and `.rpm` packages which can't be easily replicated with GNU autotools or Make. It is possible to use https://github.com/jordansissel/fpm to create packages but I really don't want to have to pull ruby gems. CPack works perfectly fine for now.

**Comment by owl4ce** [comment]
###### out-of-topic
Starting my own [port for OpenRC init](https://github.com/owl4ce/cfs-zen-tweaks-openrc). I don't know how to configure multiple system init in one `CMakeLists.txt`.

**Comment by igo95862** [comment]
I pushed a commit https://github.com/igo95862/cfs-zen-tweaks/commit/54d3cf2c7dd10084adc1a1a5c4d04264adf773d6 to make it POSIX shell compatible. Might do a version 1.3.0 release.
