### ISSUE TITLE
openSUSE: unit file needs to be in /usr/ not /usr/local

### ISSUE THREAD

**Issue by tamara-schmitz** [igo95862/cfs-zen-tweaks#7]
Hey there,
on openSUSE the service does not start during boot due to a quirk that is uncommon on over OSes.
Cmake's default install directory is /usr/local. It is probably so to distinguish between files from packages vs files from the local builds.

The /usr/local directory is mounted as a BTRFS subvolume meaning that it is not visible to Systemd until later on in the boot process.
Subvolumes are used to exclude certain directories from regular snapshotting that Btrfs does. This is done so to avoid including user data in snapshots and therefore making them bigger. I guess since it's the Cmake default it's also considered user data.

I'm not the person who usually packages stuff since this thankfully not a C project, I'm going to package this soonish. The openSUSE build system probably deals with this stuff already.

My point. Can we add a little note to the README just telling openSUSE users to run `cmake -DCMAKE_INSTALL_PREFIX=/usr .`? I would very much appreciate that for future reference.

**Comment by igo95862** [comment]
Have you tried running RPM package from releases page? It uses `/usr/sbin`.

**Comment by igo95862** [comment]
> My point. Can we add a little note to the README just telling openSUSE users to run `cmake -DCMAKE_INSTALL_PREFIX=/usr .`? I would very much appreciate that for future reference.

I think I would rather create a wiki page with distro specific advice. Really want to keep the README short as possible.

**Comment by igo95862** [comment]
> The /usr/local directory is mounted as a BTRFS subvolume meaning that it is not visible to Systemd until later on in the boot process.

So `/usr/local` is not a part of fstab but mounted by some other service? Is that a mount unit? If it is when it should mount together with all `local-fs.target` before any multi-user services start. Kind of feels like OpenSUSE bug.

There is also a `RequiresMountsFor=` systemd option to ensure a mount is available. (can be added as an override)

**Comment by tamara-schmitz** [comment]
> So `/usr/local` is not a part of fstab but mounted by some other service? Is that a mount unit?

No it is in the fstab. And the service shows up when I run `systemctl status set-cfs-tweaks.service`. But it never runs on boot, only manually. Or when I install it under /usr not /usr/local.

Btrfs subvolumes are mounted after the root Btrfs fs is mounted.

And I just checked using `lsinitrd` aka `lsinitramfs`. I'm trying to understand how systemd works. The initramfs contains only the bare minimum of targets and services. So I assume that the other services are started after the rootfs has been mounted. But I guess systemd doesn't consider the files in `/usr/local` for the current boot process.

**Comment by tamara-schmitz** [comment]
It's normal for the fstab on SUSE to look like this:
```
/dev/system/root  /                       btrfs  defaults,compress=zstd         0  0
/dev/system/root  /.snapshots             btrfs  subvol=/@/.snapshots           0  0
/dev/system/root  /var                    btrfs  subvol=/@/var                  0  0
/dev/system/root  /usr/local              btrfs  subvol=/@/usr/local           0  0
/dev/system/root  /tmp                    btrfs  subvol=/@/tmp                 0  0
/dev/system/root  /srv                    btrfs  subvol=/@/srv                 0  0
/dev/system/root  /root                   btrfs  subvol=/@/root                0  0
/dev/system/root  /opt                    btrfs  subvol=/@/opt                 0  0
/dev/system/root  /home                   btrfs  subvol=/@/home                0  0
/dev/system/root  /boot/grub2/x86_64-efi  btrfs  subvol=/@/boot/grub2/x86_64-efi  0  0
/dev/system/root  /boot/grub2/i386-pc     btrfs  subvol=/@/boot/grub2/i386-pc  0  0
```

**Comment by tamara-schmitz** [comment]
> Have you tried running RPM package from releases page? It uses `/usr/sbin`.

I will do that

**Comment by igo95862** [comment]
> And I just checked using `lsinitrd` aka `lsinitramfs`. I'm trying to understand how systemd works. The initramfs contains only the bare minimum of targets and services. So I assume that the other services are started after the rootfs has been mounted. But I guess systemd doesn't consider the files in `/usr/local` for the current boot process.

I looked in to it and I think the issue is that initrd does not mount `/usr/local` before handing the root filesystem to systemd.

Not sure that initrd generator does OpenSUSE use. Might be `dracut`. I would check what initrd actually mounts and see if it possible to modify that.

**Comment by tamara-schmitz** [comment]
> > And I just checked using `lsinitrd` aka `lsinitramfs`. I'm trying to understand how systemd works. The initramfs contains only the bare minimum of targets and services. So I assume that the other services are started after the rootfs has been mounted. But I guess systemd doesn't consider the files in `/usr/local` for the current boot process.
> 
> I looked in to it and I think the issue is that initrd does not mount `/usr/local` before handing the root filesystem to systemd.
> 
> Not sure that initrd generator does OpenSUSE use. Might be `dracut`. I would check what initrd actually mounts and see if it possible to modify that.

Interesting and very educational.

dracut is indeed used. `initrd` is SUSE's name for their script I guess, perhaps a legacy thing xD. Ubuntu calls it `mkinitramfs`, Arch `mkinitcpio`.

Well I guess no README update and I'll just package this for openSUSE ;)

**Comment by igo95862** [comment]
> Well I guess no README update

I added a wiki page: https://github.com/igo95862/cfs-zen-tweaks/wiki
